### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by zeffii** [zeffii/air_tracker#16]
Some of these may be implemented early and  require re-implementation as my understanding of C++/SDL develops.
- [x] draw pattern, arbitrary from a file.
- [x] edit pattern (input notes, change octave colunm, new hex values, remove values, note off, note cut)
- [x] pattern based current octave for new nodes
- [x] implement selection rectangle
- [x] function to interpolate between two hex vales.
- [ ]  function to interpolate between multiple values over the selection.
- [ ]  function to rescale values in selection
- [ ]  switch pattern next/last for this machine
- [ ]  scroll pattern
- [ ]  add sequencer view

**Comment by zeffii** [comment]
While i'm not finished the pattern editing stuff, that's one area of the whole project that i'm confident I can fully grasp and make an intuitive interface. Therefor it;s time to shift gears and tackle things that i've been putting off.
- adsr / NNA , controlled via keyboard ( i really don't care much for mouse control )
- how to get sound out of this,, (scares me a little..)

**Comment by zeffii** [comment]
Sound is the endgoal of this thing, and it's time to figure out how to implement that part of it.
- CSOUND lib ?
- SUNVOX lib ?
- STK ?

**Comment by zeffii** [comment]
maybe a Bela / beagle bone unit driven?

**Comment by zeffii** [comment]
The bela tutorials are a good resource for learning about waveform reading / playing. I think i have everything I need now to start exclusively looking at how to get sound out of this thing. Anything else I do now that isn't directly sound related will be merely procastination. I don't want to use JUCE,  but might.. or the other libraries above.
